# Generated by Django 4.2.1 on 2023-05-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=3, max_digits=50)),
                ('imge', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('description', models.TextField()),
            ],
        ),
    ]
