# Generated by Django 4.2.1 on 2023-05-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
