# Generated by Django 4.2.1 on 2023-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('shop', '0005_category_remove_product_category_alter_product_imge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
